### ISSUE TITLE
Files for test and environment to run

### ISSUE THREAD

**Issue by HqWei** [irfanICMLL/CoupleGenerator#1]
Can you provide your checkpoint model ? And environment details,for example,tensorflow version

**Comment by ilovefuju** [comment]
just run `sh autotest.sh`. I use `tensorflow=1.14.0`

**Comment by HqWei** [comment]
The npy files for VGG16 NPY can not be download, can you provide the file for me.

**Comment by irfanICMLL** [comment]
Please refer to this project: https://github.com/machrisaa/tensorflow-vgg

**Comment by irfanICMLL** [comment]
This project is a toy project from two years ago. I found it in my history files. Therefore I can not remember the details for the training environment. Maybe it is based on tf1.1.
