### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by Shuhui-Guo** [irfanICMLL/CoupleGenerator#2]
Shape mismatch in tuple component 1. Expected [512,512,3], got [512,512,4]
         [[{{node batch/fifo_queue_enqueue}}]]
![image](https://user-images.githubusercontent.com/39852159/71898424-3c9c0480-3194-11ea-88fc-06226fdeb8fa.png)

**Comment by Shuhui-Guo** [comment]
I have already settled the model in my_ngg folder and myself photo in dataset folder.  But I don't know why this error will happen.

**Comment by irfanICMLL** [comment]
The image you use may have 4 channels. You can preprocess the image  into  three channels
