### ISSUE TITLE
Always get save_path error

### ISSUE THREAD

**Issue by ilovefuju** [irfanICMLL/CoupleGenerator#3]
![Screenshot from 2020-01-08 08-38-42](https://user-images.githubusercontent.com/53335269/71940790-9a5f3980-31f2-11ea-8ac9-8bb4b07c76a6.png)
when a.checkpoint is not None, it will read checkpoint from the dir.
However, the dir is new created and always has files.

**Comment by irfanICMLL** [comment]
I am not quite sure what is the problem. 
Run 
python train.py --output './train_out_0428/'  --mode train --input_dir './test_pic/'

If you do not have a folder named './train_out_0428/', it will not load the ckpt.

**Comment by ilovefuju** [comment]
Hi, solved the problem with 8800th checkpoint downloaded. thx.
