### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by YuriZhirkov** [irfanICMLL/CoupleGenerator#4]
请问怎么项目怎么部署在服务器中，
有快速开始的文档吗？依赖的环境和注意事项，
可以把这个项目使用在相亲项目中吗

**Comment by irfanICMLL** [comment]
It is a toy project. If you want to use it for business, you need to collect more data through the link I provided.

**Comment by YuriZhirkov** [comment]
谢谢啦大牛，感觉这个项目可以为相亲项目提供一种互动与用户体验！哈哈
