### ISSUE TITLE
FileNotFoundError:  vgg16.npy 

### ISSUE THREAD

**Issue by xiaohaoChen** [irfanICMLL/CoupleGenerator#6]

**Comment by irfanICMLL** [comment]
See the environments in README

You also need to download the pretrain weight for vgg through following links:

https://github.com/machrisaa/tensorflow-vgg

**Comment by xiaohaoChen** [comment]
> See the environments in README
> 
> You also need to download the pretrain weight for vgg through following links:
> 
> https://github.com/machrisaa/tensorflow-vgg

thanks!
